# Set the monitor password to match upsd.users [monitor] on the Pi after deploy
MONITOR cyberpower@192.168.1.228 1 monitor <to-be-set> secondary

SHUTDOWNCMD "/sbin/shutdown -h +0"

POLLFREQ 5
POLLFREQALERT 2
DEADTIME 15
FINALDELAY 5
