# Set the admin password to match upsd.users after deploy
MONITOR cyberpower@localhost 1 admin <to-be-set> primary

SHUTDOWNCMD "/etc/nut/shutdown-ups.sh"

NOTIFYFLAG ONBATT SYSLOG+WALL
NOTIFYFLAG ONLINE SYSLOG+WALL
NOTIFYFLAG LOWBATT SYSLOG+WALL

POLLFREQ 5
POLLFREQALERT 2
HOSTSYNC 15
DEADTIME 15
FINALDELAY 5
